# Generated by Django 2.1.3 on 2018-11-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=20)),
                ('hair_color', models.CharField(max_length=10)),
            ],
        ),
    ]
